# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://notes.clockwisemd.com" # the base hostname & protocol for your site
timezone: America/New_York

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Clockwise.MD Release Notes
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "Release notes for Clockwise.MD" # used by search engines

  # Header and footer text
  header_text: >
    <p>Welcome to the Clockwise.MD Release Notes site.</p>

    <p>Find out about upcoming and latest changes to Clockwise.</p>
  header_text_feature_image:
  footer_text: >
    Visit <a href="https://www.clockwisemd.com">Clockwise.MD</a> or view our <a href="http://status.clockwisemd.com">Site Status</a>

  # Icons
  rss: true
  email_address: "support@clockwisemd.com" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "LightshedHealth/release_notes"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "ClockwiseMD"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

sass:
  sass_dir: _sass
  style: :compressed
gems:
  - jekyll-paginate
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
